2024-10-14 14:44:11,279 INFO    MainThread:646437 [wandb_setup.py:_flush():79] Current SDK version is 0.18.3
2024-10-14 14:44:11,279 INFO    MainThread:646437 [wandb_setup.py:_flush():79] Configure stats pid to 646437
2024-10-14 14:44:11,279 INFO    MainThread:646437 [wandb_setup.py:_flush():79] Loading settings from /data/ephemeral/home/.config/wandb/settings
2024-10-14 14:44:11,279 INFO    MainThread:646437 [wandb_setup.py:_flush():79] Loading settings from /data/ephemeral/home/Jungyeon/level2-objectdetection-cv-07/wandb/settings
2024-10-14 14:44:11,279 INFO    MainThread:646437 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-10-14 14:44:11,279 INFO    MainThread:646437 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-10-14 14:44:11,279 INFO    MainThread:646437 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'mmdetection/train.py', 'program_abspath': '/data/ephemeral/home/Jungyeon/level2-objectdetection-cv-07/mmdetection/train.py', 'program': '/data/ephemeral/home/Jungyeon/level2-objectdetection-cv-07/mmdetection/train.py'}
2024-10-14 14:44:11,279 INFO    MainThread:646437 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-10-14 14:44:11,279 INFO    MainThread:646437 [wandb_init.py:_log_setup():532] Logging user logs to /data/ephemeral/home/Jungyeon/level2-objectdetection-cv-07/wandb/run-20241014_144411-mkgibzwt/logs/debug.log
2024-10-14 14:44:11,279 INFO    MainThread:646437 [wandb_init.py:_log_setup():533] Logging internal logs to /data/ephemeral/home/Jungyeon/level2-objectdetection-cv-07/wandb/run-20241014_144411-mkgibzwt/logs/debug-internal.log
2024-10-14 14:44:11,279 INFO    MainThread:646437 [wandb_init.py:init():617] calling init triggers
2024-10-14 14:44:11,279 INFO    MainThread:646437 [wandb_init.py:init():624] wandb.init called with sweep_config: {}
config: {}
2024-10-14 14:44:11,279 INFO    MainThread:646437 [wandb_init.py:init():667] starting backend
2024-10-14 14:44:11,279 INFO    MainThread:646437 [wandb_init.py:init():671] sending inform_init request
2024-10-14 14:44:11,283 INFO    MainThread:646437 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-10-14 14:44:11,284 INFO    MainThread:646437 [wandb_init.py:init():684] backend started and connected
2024-10-14 14:44:11,290 INFO    MainThread:646437 [wandb_init.py:init():779] updated telemetry
2024-10-14 14:44:11,295 INFO    MainThread:646437 [wandb_init.py:init():812] communicating run to backend with 90.0 second timeout
2024-10-14 14:44:11,560 ERROR   MainThread:646437 [wandb_init.py:init():838] encountered error: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-10-14 14:44:11,560 ERROR   MainThread:646437 [wandb_init.py:init():1262] error in wandb.init()
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1252, in init
    return wi.init()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 844, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-10-14 14:44:13,567 WARNING MsgRouterThr:646437 [router.py:message_loop():77] message_loop has been closed
